// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	queue "gitlab.id.vin/gami/gami-common/adapters/queue"
)

// KafkaProducer is an autogenerated mock type for the KafkaProducer type
type KafkaProducer struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *KafkaProducer) Close() {
	_m.Called()
}

// SendMessage provides a mock function with given fields: _a0
func (_m *KafkaProducer) SendMessage(_a0 *queue.KafkaMessage) {
	_m.Called(_a0)
}

// SendMessageAsync provides a mock function with given fields: message
func (_m *KafkaProducer) SendMessageAsync(message *queue.KafkaMessage) {
	_m.Called(message)
}

// SendMessageSync provides a mock function with given fields: message
func (_m *KafkaProducer) SendMessageSync(message *queue.KafkaMessage) error {
	ret := _m.Called(message)

	var r0 error
	if rf, ok := ret.Get(0).(func(*queue.KafkaMessage) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewKafkaProducer interface {
	mock.TestingT
	Cleanup(func())
}

// NewKafkaProducer creates a new instance of KafkaProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewKafkaProducer(t mockConstructorTestingTNewKafkaProducer) *KafkaProducer {
	mock := &KafkaProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
