// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	queue "gitlab.id.vin/gami/gami-common/adapters/queue"
)

// KafkaConsumerHandlerFunc is an autogenerated mock type for the KafkaConsumerHandlerFunc type
type KafkaConsumerHandlerFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: message
func (_m *KafkaConsumerHandlerFunc) Execute(message *queue.ConsumerMessage) {
	_m.Called(message)
}

type mockConstructorTestingTNewKafkaConsumerHandlerFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewKafkaConsumerHandlerFunc creates a new instance of KafkaConsumerHandlerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewKafkaConsumerHandlerFunc(t mockConstructorTestingTNewKafkaConsumerHandlerFunc) *KafkaConsumerHandlerFunc {
	mock := &KafkaConsumerHandlerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
